package main

import (
	"net/http"
	"testing"
	"time"
)

func (a *testApp) headroom(t *testing.T) headroomReport {
	t.Helper()
	var got headroomReport
	if res := a.get(t, headroomPath, &got); res.StatusCode != http.StatusOK {
		t.Fatalf("GET %s = %d, want 200", headroomPath, res.StatusCode)
	}
	return got
}

func assertHeadroom(t *testing.T, got headroomReport, want []headroomMonth) {
	t.Helper()
	if !got.Available {
		t.Fatal("available = false, want true")
	}
	if len(got.Months) != len(want) {
		t.Fatalf("got %d months, want %d: %+v", len(got.Months), len(want), got.Months)
	}
	for i, w := range want {
		g := got.Months[i]
		if g.Month != w.Month || g.HeadroomCents != w.HeadroomCents || g.RunningCents != w.RunningCents {
			t.Errorf("month %d = %s %d %d, want %s %d %d", i,
				g.Month, g.HeadroomCents, g.RunningCents, w.Month, w.HeadroomCents, w.RunningCents)
		}
	}
}

// Goal is a buffer, not a debt: the household's own table (Goal 500).
func TestGoalBuffer(t *testing.T) {
	for leftover, want := range map[int64]int64{
		800: 300, 501: 1, 500: 0, 200: 0, 0: 0, -300: 0, -500: 0, -600: -100,
	} {
		if got := goalBuffer(leftover, 500); got != want {
			t.Errorf("goalBuffer(%d, 500) = %d, want %d", leftover, got, want)
		}
	}
}

// The horizon is the rest of the year, at least one month and at most six.
func TestHeadroomHorizonIsTheRestOfTheYear(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	for _, m := range []string{"2025-10", "2025-11", "2025-12"} {
		a.addExpense(t, map[string]any{"occurred_on": m + "-10", "amount_cents": 1000, "category_id": alimentari.ID})
	}
	for clock, want := range map[time.Time][]string{
		time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC):  {"2026-04", "2026-09"},
		time.Date(2026, 9, 15, 0, 0, 0, 0, time.UTC):  {"2026-10", "2026-12"},
		time.Date(2026, 11, 15, 0, 0, 0, 0, time.UTC): {"2026-12", "2026-12"},
		time.Date(2026, 12, 15, 0, 0, 0, 0, time.UTC): {"2027-01", "2027-01"},
	} {
		a.setNow(t, clock)
		got := a.headroom(t).Months
		if len(got) == 0 || got[0].Month != want[0] || got[len(got)-1].Month != want[1] {
			t.Errorf("at %s: months %+v, want %s to %s", clock.Format("2006-01"), got, want[0], want[1])
		}
	}
}

// The running total starts from last month's actual leftover (clock at
// 2026-03-15, so February): 100000 salary + 40000 Contract Income, minus
// 20000 groceries, a 5000 PAC buy and the 30000 rent its Recurring expense
// generates for February — generated by the report itself, no screen having
// read February — and the 50000 investment sale left out: 85000 left, Goal
// 10000 → 75000.
func TestHeadroomStartsFromLastMonthsActualLeftover(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	casa := a.category(t, "Casa")
	stipendio := a.category(t, seedStipendioName)
	investments := a.investments(t)
	for _, m := range []string{"2025-12", "2026-01"} {
		a.addExpense(t, map[string]any{"occurred_on": m + "-10", "amount_cents": 1000, "category_id": alimentari.ID})
	}

	a.setNow(t, time.Date(2026, 2, 1, 0, 0, 0, 0, time.UTC))
	a.addRecurring(t, map[string]any{"amount_cents": 30000, "category_id": casa.ID, "day_of_month": 20})
	a.setNow(t, testClock)

	a.addExpense(t, map[string]any{"occurred_on": "2026-02-10", "amount_cents": 20000, "category_id": alimentari.ID})
	a.addExpense(t, map[string]any{"occurred_on": "2026-02-11", "amount_cents": 5000, "category_id": investments.ID})
	a.addIncome(t, map[string]any{"amount_cents": 100000, "category_id": stipendio.ID, "payment_date": "2026-02-27"})
	client := a.createClient(t, "Acme")
	contract := a.createContract(t, client.ID, map[string]any{"start_month": "2026-01", "end_month": "2026-02", "total_cents": 40000})
	a.addIncome(t, map[string]any{
		"amount_cents": 40000, "category_id": a.freelance(t).ID, "client_id": client.ID,
		"contract_id": contract.ID, "payment_date": "2026-02-15", "bollo_fattura": false,
	})
	vwce := a.createHolding(t, "VWCE", holdingETF)
	a.addIncome(t, map[string]any{"amount_cents": 50000, "category_id": investments.ID, "holding_id": vwce.ID, "payment_date": "2026-02-20"})
	if res := a.put(t, settingsPath, map[string]any{"goal_cents": int64(10000)}, nil); res.StatusCode != http.StatusOK {
		t.Fatalf("PUT goal = %d, want 200", res.StatusCode)
	}

	got := a.headroom(t)
	if got.StartCents != 75000 {
		t.Fatalf("start = %d, want 75000", got.StartCents)
	}
	if first := got.Months[0]; first.RunningCents != got.StartCents+first.HeadroomCents {
		t.Errorf("first running = %d, want start %d + headroom %d", first.RunningCents, got.StartCents, first.HeadroomCents)
	}
}

// The baseline blend, clock at 2026-03-15 (two months of 2026 over, so the
// last 12 months weigh 10/12): 100000 of spending a month in Oct–Dec 2025,
// 40000 in Jan–Feb 2026. Trailing median 100000, this year's 40000 →
// (10×100000 + 2×40000) / 12 = 90000 typical spending, and the breakdown
// says so.
func TestHeadroomBlendsTheLast12MonthsWithThisYear(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	for day, cents := range map[string]int64{
		"2025-10-10": 100000, "2025-11-10": 100000, "2025-12-10": 100000,
		"2026-01-10": 40000, "2026-02-10": 40000,
	} {
		a.addExpense(t, map[string]any{"occurred_on": day, "amount_cents": cents, "category_id": alimentari.ID})
	}

	got := a.headroom(t)
	if got.TypicalSpendingCents != 90000 {
		t.Errorf("typical spending = %d, want 90000", got.TypicalSpendingCents)
	}
	if got.TrailingWeightPercent != 83 {
		t.Errorf("trailing weight = %d%%, want 83%% (10/12)", got.TrailingWeightPercent)
	}
	if got.Months[0].HeadroomCents != -90000 {
		t.Errorf("April headroom = %d, want -90000", got.Months[0].HeadroomCents)
	}

	// In January nothing of the new year is over: the last 12 months alone.
	a.setNow(t, time.Date(2026, 1, 15, 0, 0, 0, 0, time.UTC))
	if jan := a.headroom(t); jan.TypicalSpendingCents != 100000 || jan.TrailingWeightPercent != 100 {
		t.Errorf("January: typical %d at %d%%, want 100000 at 100%%", jan.TypicalSpendingCents, jan.TrailingWeightPercent)
	}
}

// The breakdown's per-month parts are what the Headroom was built from.
func TestHeadroomMonthCarriesItsContractAndRecurringParts(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	casa := a.category(t, "Casa")
	for _, m := range []string{"2025-12", "2026-01", "2026-02"} {
		a.addExpense(t, map[string]any{"occurred_on": m + "-10", "amount_cents": 1000, "category_id": alimentari.ID})
	}
	a.addRecurring(t, map[string]any{"amount_cents": 85000, "category_id": casa.ID, "day_of_month": 5})
	client := a.createClient(t, "Acme")
	a.createContract(t, client.ID, map[string]any{"start_month": "2026-01", "end_month": "2026-06", "total_cents": 90000})

	april := a.headroom(t).Months[0]
	if april.RecurringCents != 85000 || april.ContractCents != 30000 {
		t.Errorf("April parts = recurring %d, contract %d, want 85000 and 30000", april.RecurringCents, april.ContractCents)
	}
}

// The whole formula in one household, clock at 2026-03-15, history since
// 2025-12 (three completed months: Dec, Jan, Feb):
//
//   - typical Income: Stipendio 200000 every month; the Contract Income and
//     the Investments sale are left out → median 200000
//   - typical non-recurring spending: 50000 / 70000 / 60000+10000
//     Investments → median 70000; the rent Expenses the Recurring expense
//     generated in Jan and Feb are left out
//   - Contract Jan–Jun, 120000 total, 30000 received → 90000 owed over
//     Apr–Jun = 30000 a month, nothing after June
//   - Recurring: rent 85000 ongoing, gym 5000 ending in May
//   - Goal 40000
//   - Start: February actually left 200000 − (60000 + 10000 + 85000 rent) =
//     45000, through the Goal → 5000
func TestHeadroomProjectsTheNextSixMonths(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	casa := a.category(t, "Casa")
	stipendio := a.category(t, seedStipendioName)
	investments := a.investments(t)

	// The rent, generated in January and February (each month materialises
	// when a report reads it).
	a.setNow(t, time.Date(2026, 1, 10, 0, 0, 0, 0, time.UTC))
	a.addRecurring(t, map[string]any{"amount_cents": 85000, "category_id": casa.ID, "day_of_month": 5})
	a.get(t, "/api/reports/month/2026-01", nil)
	a.setNow(t, time.Date(2026, 2, 10, 0, 0, 0, 0, time.UTC))
	a.get(t, "/api/reports/month/2026-02", nil)
	a.setNow(t, testClock)

	gym := a.addRecurring(t, map[string]any{"amount_cents": 5000, "category_id": casa.ID, "day_of_month": 1})
	if res := a.patch(t, recurringPath(gym.ID), map[string]any{"end_month": "2026-05"}, nil); res.StatusCode != http.StatusOK {
		t.Fatalf("ending the gym = %d, want 200", res.StatusCode)
	}

	for _, e := range []struct {
		day   string
		cents int64
		cat   int64
	}{
		{"2025-12-10", 50000, alimentari.ID},
		{"2026-01-10", 70000, alimentari.ID},
		{"2026-02-10", 60000, alimentari.ID},
		{"2026-02-12", 10000, investments.ID},
	} {
		a.addExpense(t, map[string]any{"occurred_on": e.day, "amount_cents": e.cents, "category_id": e.cat})
	}
	for _, day := range []string{"2025-12-27", "2026-01-27", "2026-02-27"} {
		a.addIncome(t, map[string]any{"amount_cents": 200000, "category_id": stipendio.ID, "payment_date": day})
	}

	client := a.createClient(t, "Acme")
	contract := a.createContract(t, client.ID, map[string]any{
		"start_month": "2026-01", "end_month": "2026-06", "total_cents": 120000,
	})
	a.addIncome(t, map[string]any{
		"amount_cents": 30000, "category_id": a.freelance(t).ID, "client_id": client.ID,
		"contract_id": contract.ID, "payment_date": "2026-01-31", "bollo_fattura": false,
	})
	vwce := a.createHolding(t, "VWCE", holdingETF)
	a.addIncome(t, map[string]any{
		"amount_cents": 50000, "category_id": investments.ID, "holding_id": vwce.ID, "payment_date": "2026-02-20",
	})

	if res := a.put(t, settingsPath, map[string]any{"goal_cents": int64(40000)}, nil); res.StatusCode != http.StatusOK {
		t.Fatalf("PUT goal = %d, want 200", res.StatusCode)
	}

	// 130000 typical; +30000 Contract through June; −85000 rent; −5000 gym
	// through May; −40000 Goal.
	assertHeadroom(t, a.headroom(t), []headroomMonth{
		{Month: "2026-04", HeadroomCents: 30000, RunningCents: 35000},
		{Month: "2026-05", HeadroomCents: 30000, RunningCents: 65000},
		{Month: "2026-06", HeadroomCents: 35000, RunningCents: 100000},
		{Month: "2026-07", HeadroomCents: 5000, RunningCents: 105000},
		{Month: "2026-08", HeadroomCents: 5000, RunningCents: 110000},
		{Month: "2026-09", HeadroomCents: 5000, RunningCents: 115000},
	})
}

// A month that costs more than it brings shows negative and eats into what
// the earlier months accumulated.
func TestHeadroomNegativeMonthLowersTheRunningTotal(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	stipendio := a.category(t, seedStipendioName)
	for _, m := range []string{"2025-12", "2026-01", "2026-02"} {
		a.addExpense(t, map[string]any{"occurred_on": m + "-10", "amount_cents": 100000, "category_id": alimentari.ID})
		a.addIncome(t, map[string]any{"amount_cents": 150000, "category_id": stipendio.ID, "payment_date": m + "-27"})
	}
	// Typical 50000 a month; a heavy 80000 Recurring expense running only
	// through April makes April 50000 − 80000 = −30000.
	heavy := a.addRecurring(t, map[string]any{"amount_cents": 80000, "category_id": alimentari.ID, "day_of_month": 1})
	if res := a.patch(t, recurringPath(heavy.ID), map[string]any{"end_month": "2026-04"}, nil); res.StatusCode != http.StatusOK {
		t.Fatalf("ending it = %d, want 200", res.StatusCode)
	}

	// February actually left 50000, the start; April's −30000 eats into it.
	assertHeadroom(t, a.headroom(t), []headroomMonth{
		{Month: "2026-04", HeadroomCents: -30000, RunningCents: 20000},
		{Month: "2026-05", HeadroomCents: 50000, RunningCents: 70000},
		{Month: "2026-06", HeadroomCents: 50000, RunningCents: 120000},
		{Month: "2026-07", HeadroomCents: 50000, RunningCents: 170000},
		{Month: "2026-08", HeadroomCents: 50000, RunningCents: 220000},
		{Month: "2026-09", HeadroomCents: 50000, RunningCents: 270000},
	})
}

// Budget's rule: fewer than three months of history, no projection.
func TestHeadroomUnavailableWithoutThreeMonthsOfHistory(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	a.addExpense(t, map[string]any{"occurred_on": "2026-01-10", "amount_cents": 1000, "category_id": alimentari.ID})

	got := a.headroom(t)
	if got.Available || len(got.Months) != 0 {
		t.Fatalf("got %+v, want unavailable with no months", got)
	}
}

func months(running ...int64) []headroomMonth {
	names := nextMonths(func() time.Time { return testClock }, len(running))
	out := make([]headroomMonth, len(running))
	for i, r := range running {
		out[i] = headroomMonth{Month: names[i], RunningCents: r}
	}
	return out
}

func purchases(amounts ...int64) []plannedPurchase {
	out := make([]plannedPurchase, len(amounts))
	for i, a := range amounts {
		out[i] = plannedPurchase{ID: int64(i + 1), AmountCents: a, Position: int64(i + 1)}
	}
	return out
}

// Priority decides who gets Headroom first, and a placed purchase uses up
// its amount from its month on.
func TestPlaceInPriorityOrder(t *testing.T) {
	// Running 100, 200, 300, 400, 500, 600.
	got := place(months(100, 200, 300, 400, 500, 600), purchases(150, 150), 0)
	// The first fits from May (200); after it the balance is 100, 50, 150,
	// 250, 350, 450, so the second fits from June (exactly 150).
	if got[0].Month != "2026-05" || got[1].Month != "2026-06" {
		t.Fatalf("placed in %q and %q, want 2026-05 and 2026-06", got[0].Month, got[1].Month)
	}
}

// One that doesn't fit consumes nothing: the smaller one after it still
// lands, and the gap is measured against the balance at the end of the
// horizon after higher-priority placements.
func TestPlaceSkipsWithoutBlocking(t *testing.T) {
	got := place(months(100, 200, 300, 400, 500, 600), purchases(100, 5000, 50), 1000)
	if got[0].Month != "2026-04" {
		t.Errorf("first placed in %q, want 2026-04", got[0].Month)
	}
	if got[1].Month != "" {
		t.Fatalf("the 5000 one placed in %q, want it not to fit", got[1].Month)
	}
	// 600 - 100 (the first) = 500 left at the end, so 4500 missing.
	if got[1].MissingCents != 4500 {
		t.Errorf("missing = %d, want 4500", got[1].MissingCents)
	}
	if got[1].SavingsCover {
		t.Error("savings 1000 reported as covering a 4500 gap")
	}
	// The first used all of April, so the 50 one lands in May, where the
	// balance (100) covers it. Blocked by the skipped one, it would land nowhere.
	if got[2].Month != "2026-05" {
		t.Errorf("the 50 one placed in %q, want 2026-05: the skipped one must not block it", got[2].Month)
	}
}

// A negative accumulated Headroom is a deficit on top of the price, not a
// zero: running ending at -500, a 400 purchase is 900 short.
func TestPlaceGapIncludesANegativeBalance(t *testing.T) {
	got := place(months(-100, -200, -300, -400, -500, -500), purchases(400), 1000)
	if got[0].Month != "" || got[0].MissingCents != 900 || !got[0].SavingsCover {
		t.Fatalf("got %+v, want not placed, 900 missing, covered by 1000 savings", got[0])
	}
}

func TestPlaceSavingsCoverTheGap(t *testing.T) {
	got := place(months(100, 100, 100, 100, 100, 100), purchases(400), 300)
	if got[0].Month != "" || got[0].MissingCents != 300 || !got[0].SavingsCover {
		t.Fatalf("got %+v, want not placed, 300 missing, covered by 300 savings", got[0])
	}
}

// A later negative month must not push the account below zero after
// buying: the purchase waits until the balance holds from then on.
func TestPlaceWaitsOutALaterDip(t *testing.T) {
	// Running 300, 300, 100 (a bad month), 200, 300, 400.
	got := place(months(300, 300, 100, 200, 300, 400), purchases(250), 0)
	if got[0].Month != "2026-08" {
		t.Fatalf("placed in %q, want 2026-08, the first month the balance stays at 250 or more", got[0].Month)
	}
}

// With no history the report is unavailable and places nothing, even with
// Planned purchases saved.
func TestHeadroomPlacementsEmptyWhenUnavailable(t *testing.T) {
	a := newTestApp(t)
	a.addPlanned(t, "Laptop", 150000)
	got := a.headroom(t)
	if got.Available || len(got.Placements) != 0 {
		t.Fatalf("got %+v, want unavailable with no placements", got)
	}
}

// End to end: the endpoint places the saved list with the household's real
// Savings.
func TestHeadroomReportPlacesThePlannedPurchases(t *testing.T) {
	a := newTestApp(t)
	alimentari := a.category(t, "Alimentari")
	stipendio := a.category(t, seedStipendioName)
	for _, m := range []string{"2025-12", "2026-01", "2026-02"} {
		a.addExpense(t, map[string]any{"occurred_on": m + "-10", "amount_cents": 100000, "category_id": alimentari.ID})
		a.addIncome(t, map[string]any{"amount_cents": 150000, "category_id": stipendio.ID, "payment_date": m + "-27"})
	}
	// Start 50000 (February's leftover) plus 50000 a month, so running
	// 100000 ... 350000. Savings: 3 x 50000.
	laptop := a.addPlanned(t, "Laptop", 120000)
	car := a.addPlanned(t, "Auto", 500000)

	got := a.headroom(t).Placements
	if len(got) != 2 {
		t.Fatalf("got %d placements, want 2", len(got))
	}
	if got[0].PlannedID != laptop.ID || got[0].Month != "2026-05" {
		t.Errorf("laptop = %+v, want placed in 2026-05 (running 150000 covers 120000)", got[0])
	}
	// 350000 - 120000 = 230000 left, so 270000 missing; Savings 150000 don't cover it.
	if got[1].PlannedID != car.ID || got[1].Month != "" || got[1].MissingCents != 270000 || got[1].SavingsCover {
		t.Errorf("car = %+v, want not placed, 270000 missing, not covered", got[1])
	}
}
