#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

REPO="blazardsky/sonic-finance-pi"
PI_TAILSCALE_IP="100.74.171.49"
CI_TAG="tag:ci-deploy"

TOTAL_STAGES=5

banner "Tailscale OAuth client for CI deploys"

# ── Preflight: fail loudly rather than write secrets to the wrong place ────
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  printf '%s✗ gh is not installed or not authenticated. Run `gh auth login` first.%s\n' "$RED" "$RESET"
  exit 1
fi
CURRENT_REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
if [[ "$CURRENT_REPO" != "$REPO" ]]; then
  printf '%s✗ gh resolves to "%s", expected "%s". Run this from inside the repo, or `gh repo set-default %s`.%s\n' \
    "$RED" "$CURRENT_REPO" "$REPO" "$REPO" "$RESET"
  exit 1
fi

# ── Stage 1: allow a new tag ────────────────────────────────────────────────
stage "Tailscale policy — authorize the ${CI_TAG} tag"
say "An OAuth client can only tag a new device with a tag your policy already"
say "recognizes, via a tagOwners entry. This adds that entry — same key name"
say "whether your policy file uses the older \"acls\" array or the newer"
say "\"grants\" array for the actual reachability rules below."
open_url "https://console.tailscale.com/admin/acls/file"
step "Find the \"tagOwners\" object (add one near the top if there is none)."
step "Merge in this line — don't overwrite the rest of the file:"
say ""
say "    \"${CI_TAG}\": [\"autogroup:admin\"],"
say ""
step "Save. Tailscale validates the JSON before it lets you save."
if ! confirm "Saved with ${CI_TAG} in tagOwners?"; then
  warn "Come back to this stage once it's saved — the OAuth client below depends on it."
  exit 1
fi

# ── Stage 2: confirm the tag can actually reach the Pi ──────────────────────
stage "Tailscale policy — confirm ${CI_TAG} can reach the Pi"
say "Same page. Look at whichever of these two your policy actually has —"
say "newer tailnets use \"grants\", older ones use \"acls\":"
say ""
say '  grants:  {"src": ["*"], "dst": ["*"], "ip": ["*"]}'
say '  acls:    {"action": "accept", "src": ["*"], "dst": ["*:*"]}'
say ""
say "If either wide-open default is still there, ${CI_TAG} can already reach"
say "the Pi (${PI_TAILSCALE_IP}) — nothing to change. Skip ahead."
say ""
say "If you've locked it down to specific rules instead, add one of:"
say ""
say "  grants:  {\"src\": [\"${CI_TAG}\"], \"dst\": [\"${PI_TAILSCALE_IP}\"], \"ip\": [\"22\"]},"
say "  acls:    {\"action\": \"accept\", \"src\": [\"${CI_TAG}\"], \"dst\": [\"${PI_TAILSCALE_IP}:22\"]},"
say ""
if ! confirm "Confirmed ${CI_TAG} can reach ${PI_TAILSCALE_IP}:22 (default rule, or the one above)?"; then
  warn "Add that rule and save before continuing — CI's SSH connection will otherwise be dropped by the tailnet policy, not by sshd."
  exit 1
fi

# ── Stage 3: create the OAuth client ────────────────────────────────────────
stage "Tailscale — generate the OAuth client"
open_url "https://console.tailscale.com/admin/settings/trust-credentials"
step "Click \"Credential\", then \"OAuth\"."
step "Under scopes, check BOTH \"Devices Core\" and \"Auth Keys\", each set to"
step "  Write. Tailscale's own troubleshooting docs call this out explicitly:"
step "  auth_keys alone mints the key, but devices:core is what's actually"
step "  checked when the key registers a tagged node — without it you get a"
step "  403 (\"calling actor does not have enough permissions\") at tailscale up."
step "Tags: add ${CI_TAG} — the client can only ever apply a tag it's been"
step "  given here, no matter what the tailnet policy above allows."
step "Click \"Generate credential\". On the \"Credential created\" page, copy"
step "  the Client ID and Client secret — the secret is shown once and never"
step "  again."
say ""
note "── reference: what should be enabled on that page ──"
note "  Scopes  → Devices Core: Write, Auth Keys: Write   (nothing else)"
note "  Tags    → ${CI_TAG}"
note "─────────────────────────────────────────────────────"
say ""
warn "If you're fixing up an existing client rather than starting fresh: some"
warn "accounts let you edit scopes/tags on it directly (open it from the list"
warn "on this page); if there's no edit option, delete it and generate a new"
warn "one — the Client ID and Secret change either way, so re-paste both below."
say ""
warn "The Client Secret is sensitive. This script reads it with hidden input"
warn "and sends it straight to GitHub as an encrypted secret — it is never"
warn "displayed, logged, or shown to anyone reviewing this session."

# ── Stage 4: capture the values and push them to GitHub ────────────────────
stage "GitHub secrets"
say "Neither value has any legitimate whitespace in it, so anything picked up"
say "by an accidental extra space or newline on copy is stripped below."

ask TS_OAUTH_CLIENT_ID "Paste the Client ID:"
TS_OAUTH_CLIENT_ID="$(printf '%s' "$TS_OAUTH_CLIENT_ID" | tr -d '[:space:]')"
if [[ -z "$TS_OAUTH_CLIENT_ID" ]]; then
  printf '%s✗ empty Client ID — nothing was saved. Re-run this script.%s\n' "$RED" "$RESET"
  exit 1
fi

ask_secret TS_OAUTH_CLIENT_SECRET "Paste the Client Secret (hidden):"
TS_OAUTH_CLIENT_SECRET="$(printf '%s' "$TS_OAUTH_CLIENT_SECRET" | tr -d '[:space:]')"
if [[ -z "$TS_OAUTH_CLIENT_SECRET" ]]; then
  printf '%s✗ empty Client Secret — nothing was saved. Re-run this script.%s\n' "$RED" "$RESET"
  exit 1
fi
# A real OAuth client secret always looks like tskey-client-<id>-<suffix> —
# catches the most common mix-up (pasting the Client ID twice, or a node
# auth key instead) before it silently becomes a wrong GitHub secret.
if [[ "$TS_OAUTH_CLIENT_SECRET" != tskey-client-* ]]; then
  warn "that doesn't look like an OAuth client secret (expected it to start"
  warn "with \"tskey-client-\") — got a prefix of: ${TS_OAUTH_CLIENT_SECRET:0:12}..."
  if ! confirm "Save it anyway?"; then
    printf '%s✗ nothing was saved. Re-run this script and re-paste the Client Secret.%s\n' "$RED" "$RESET"
    exit 1
  fi
fi

set_secret TS_OAUTH_CLIENT_ID "$TS_OAUTH_CLIENT_ID"
set_secret TS_OAUTH_CLIENT_SECRET "$TS_OAUTH_CLIENT_SECRET"

# ── Stage 5: verify ──────────────────────────────────────────────────────────
stage "Verify"
say "Confirming both secrets actually landed (names only — gh never prints values):"
gh secret list --repo "$REPO" | grep -E "^TS_OAUTH_CLIENT_ID|^TS_OAUTH_CLIENT_SECRET" || {
  printf '%s✗ one or both secrets are missing from `gh secret list`.%s\n' "$RED" "$RESET"
  exit 1
}
say ""
note "Tag used: ${CI_TAG}"
note "Pi Tailscale IP: ${PI_TAILSCALE_IP}"
note "Cross-check these against the tags:/host: values in .github/workflows/release-pi-zero.yml"

finish
